server:
  port: 8080

spring:
  application:
    name: finalProjectSpringBoot

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:3306/qr_attendance?userSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
      format_sql: true

  sql:
    init:
      mode: always